name: Deploy

on:
  push:
  pull_request:

jobs:
  Debug:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - uses: YOCKOW/Action-setup-swift@master
    - name: Install Requirements
      run: sudo apt-get install -y libssl-dev libcurl4-openssl-dev libmysqlclient-dev uuid-dev imagemagick mysql-client-5.7 && sudo sed -i -e 's/-fabi-version=2 -fno-omit-frame-pointer//g' /usr/lib/x86_64-linux-gnu/pkgconfig/mysqlclient.pc && sudo cp /usr/bin/convert /usr/local/bin
    - name: Resolve
      run: swift package resolve
    - uses: actions/cache@v1
      with:
        path: .build
        key: ${{ runner.os }}-debug-spm-${{ hashFiles('Package.resolved') }}
    - name: Build
      run: swift build -v -c debug
    - name: Publish Image
      uses: 123FLO321/github-docker-temp@0.5.0
      with:
        accessToken: ${{ secrets.GITHUB_TOKEN }}
        dockerfile: Dockerfile-localbuild-debug
  Release:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - uses: YOCKOW/Action-setup-swift@master
    - name: Install Requirements
      run: sudo apt-get install -y libssl-dev libcurl4-openssl-dev libmysqlclient-dev uuid-dev imagemagick mysql-client-5.7 && sudo sed -i -e 's/-fabi-version=2 -fno-omit-frame-pointer//g' /usr/lib/x86_64-linux-gnu/pkgconfig/mysqlclient.pc && sudo cp /usr/bin/convert /usr/local/bin
    - name: Resolve
      run: swift package resolve
    - uses: actions/cache@v1
      with:
        path: .build
        key: ${{ runner.os }}-release-spm-${{ hashFiles('Package.resolved') }}
    - name: Build
      run: swift build -v -c release
    - name: Publish Image
      uses: 123FLO321/github-docker-temp@0.5.0
      with:
        accessToken: ${{ secrets.GITHUB_TOKEN }}
        imageTagSuffix: -release
        dockerfile: Dockerfile-localbuild-release
